### Numpy Problem Set

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])


In [3]:
arr.shape

(4, 4)

In [4]:
arr.size

16

In [5]:
arr.ndim

2

In [6]:
arr.dtype

dtype('int64')

In [7]:
reshaped_array = arr.reshape(2, 8)
arr.shape

(4, 4)

In [8]:
reshaped_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [9]:
arr.sum()

np.int64(136)

In [10]:
np.mean(arr)

np.float64(8.5)

In [11]:
np.median(arr)

np.float64(8.5)

In [12]:
np.std(arr)

np.float64(4.6097722286464435)

In [13]:
arr.max()
np.unravel_index(arr.argmax(), arr.shape)

(np.int64(3), np.int64(3))

In [14]:
arr.min()
np.unravel_index(arr.argmin(), arr.shape)

(np.int64(0), np.int64(0))

In [15]:
arr.sum(axis=1)

array([10, 26, 42, 58])

In [16]:
arr.sum(axis=0)

array([28, 32, 36, 40])

In [17]:
print("First row:", arr[0])
print("Last column:", arr[:, -1])

First row: [1 2 3 4]
Last column: [ 4  8 12 16]


In [18]:
print("6, 7, 10, 11:\n", arr[1:3, 1:3])

6, 7, 10, 11:
 [[ 6  7]
 [10 11]]


In [19]:
arr[1] = [20, 21, 22, 23]
print(arr)

[[ 1  2  3  4]
 [20 21 22 23]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
np.cumsum(arr)

array([  1,   3,   6,  10,  30,  51,  73,  96, 105, 115, 126, 138, 151,
       165, 180, 196])

In [21]:
np.sort(arr.flatten())

array([ 1,  2,  3,  4,  9, 10, 11, 12, 13, 14, 15, 16, 20, 21, 22, 23])

In [22]:
arr.T

array([[ 1, 20,  9, 13],
       [ 2, 21, 10, 14],
       [ 3, 22, 11, 15],
       [ 4, 23, 12, 16]])

In [23]:
arr * arr

array([[  1,   4,   9,  16],
       [400, 441, 484, 529],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [24]:
arr[arr > 10]

array([20, 21, 22, 23, 11, 12, 13, 14, 15, 16])

In [25]:
arr[arr < 10] = 0
arr

array([[ 0,  0,  0,  0],
       [20, 21, 22, 23],
       [ 0, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
np.any(arr > 15)

np.True_

In [27]:
arr

array([[ 0,  0,  0,  0],
       [20, 21, 22, 23],
       [ 0, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
np.all(arr > 0)

np.False_